// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


var OnInstalled = /* module */[];

var Runtime = /* module */[/* OnInstalled */OnInstalled];

var Sync = /* module */[];

var Storage = /* module */[/* Sync */Sync];

var OnPageChanged = /* module */[];

var DeclarativeContent = /* module */[/* OnPageChanged */OnPageChanged];

var Tabs = /* module */[];

exports.Runtime = Runtime;
exports.Storage = Storage;
exports.DeclarativeContent = DeclarativeContent;
exports.Tabs = Tabs;
/* No side effect */
