// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


var setStyle = (
  function(element, styleKey, styleVal) {
    element.style[styleKey] = styleVal;
  }
);

var setAttribute = (
  function(element, attr, val) {
    element.setAttribute(attr, val);
  }
);

var addEventListener = (
  function(element, eventName, listener) {
    element.addEventListener(eventName, listener);
  }
);

var appendChild = (
  function(element, child) {
    element.appendChild(child);
  }
);

exports.setStyle = setStyle;
exports.setAttribute = setAttribute;
exports.addEventListener = addEventListener;
exports.appendChild = appendChild;
/* setStyle Not a pure module */
