// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Chrome$ReactTemplate = require("./Chrome.bs.js");

var myMap = { };

myMap["color"] = "green";

chrome.runtime.onInstalled.addListener((function () {
        chrome.storage.sync.set(myMap, (function () {
                console.log(myMap);
                return /* () */0;
              }));
        return /* () */0;
      }));

var rules = { };

rules["conditions"] = /* array */[Curry._1(Chrome$ReactTemplate.DeclarativeContent[/* makeNewPageStateManager */0], /* () */0)];

rules["actions"] = /* array */[Curry._1(Chrome$ReactTemplate.DeclarativeContent[/* makeNewShowPageAction */1], /* () */0)];

var rulesArr = /* array */[rules];

chrome.declarativeContent.onPageChanged.removeRules(undefined, (function () {
        chrome.declarativeContent.onPageChanged.addRules(rulesArr);
        return /* () */0;
      }));

exports.myMap = myMap;
exports.rules = rules;
exports.rulesArr = rulesArr;
/*  Not a pure module */
