// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Chrome$ReactTemplate = require("./Chrome.bs.js");

var extensionData = {
  color: "green"
};

chrome.runtime.onInstalled.addListener((function () {
        chrome.storage.sync.set(extensionData, (function () {
                console.log(extensionData);
                return /* () */0;
              }));
        return /* () */0;
      }));

var rules = { };

rules["conditions"] = /* array */[Curry._1(Chrome$ReactTemplate.DeclarativeContent[/* makeNewPageStateManager */0], "developer.chrome.com")];

rules["actions"] = /* array */[Curry._1(Chrome$ReactTemplate.DeclarativeContent[/* makeNewShowPageAction */1], /* () */0)];

var rulesArr = /* array */[rules];

chrome.declarativeContent.onPageChanged.removeRules(undefined, (function () {
        chrome.declarativeContent.onPageChanged.addRules(rulesArr);
        return /* () */0;
      }));

exports.extensionData = extensionData;
exports.rules = rules;
exports.rulesArr = rulesArr;
/*  Not a pure module */
