// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Element$ChromeExtn = require("./Element.bs.js");

var page = document.getElementById("buttonDiv");

var kButtonColors = /* array */[
  "#3aa757",
  "#e8453c",
  "#f9bb2d",
  "#4688f1"
];

function updateChromeStorageColor(color, _) {
  chrome.storage.sync.set({
        color: color
      }, (function () {
          console.log("color is " + color);
          return /* () */0;
        }));
  return /* () */0;
}

$$Array.iter((function (color) {
        Curry._2(Element$ChromeExtn.appendChild, page, Curry._3(Element$ChromeExtn.addEventListener, Curry._3(Element$ChromeExtn.setStyle, document.createElement("button"), "backgroundColor", color), "click", (function (param) {
                    return updateChromeStorageColor(color, param);
                  })));
        return /* () */0;
      }), kButtonColors);

exports.page = page;
exports.kButtonColors = kButtonColors;
exports.updateChromeStorageColor = updateChromeStorageColor;
/* page Not a pure module */
