// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

var changeColor = ( document.getElementById('changeColor') );

var updateChangeColor = (
  function(data, changeColor) {
    changeColor.style.backgroundColor = data.color;
    changeColor.setAttribute('value', data.color);
    changeColor.onclick = function(element) {
      let color = element.target.value;
      chrome.tabs.query({active: true, currentWindow: true}, function(tabs) {
        chrome.tabs.executeScript(
            tabs[0].id,
            {code: 'document.body.style.backgroundColor = "' + color + '";'});
      })
    }
  }
  );

chrome.storage.sync.get("color", (function (data) {
        return Curry._2(updateChangeColor, data, changeColor);
      }));

exports.changeColor = changeColor;
exports.updateChangeColor = updateChangeColor;
/* changeColor Not a pure module */
